### ISSUE TITLE
Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by 1Marc** [btholt/complete-intro-to-react#43] opened 2017-01-20 21:50 UTC
About 1 in 100 students are not able to load react-dom off their local file system.

If you are seeing "React is not rendered" in your index.html file with getting the "Cannot read property 'render' of undefined" error, that means the **react-dom** script is not loading from your **npm_modules** directory.

The patch for this fix if it's happening to you, is to load the file off the network vs locally through **unpkg**:

`<script src="https://unpkg.com/react-dom@15/dist/react-dom.js"></script>`

**Comment by robert-paul** [comment] 2017-03-07 19:08
Thanks for this @1Marc 👍 . I am one of those people. It actually worked fine when I first accidentally cloned the "final version" repo when I started the course, but then when I started from scratch again with the "start" branch it wasn't able to pull the react-dom script. What a puzzler! For reference, using WebStorm locally on mac.

**Comment by robert-paul** [comment] 2017-03-08 18:42
Doing `yarn add react-dom` fixed this problem and also allowed `import ReactDOM from 'react-dom'` to work properly with webpack.

**Comment by btholt** [comment] 2017-05-30 01:50
Should be resolved in v3.

**Closed by btholt** 2017-05-30 01:50 UTC

**Comment by RiyaGupta89** [comment] 2021-07-01 00:52
@1Marc The issue isn't still solved.

**Comment by RiyaGupta89** [comment] 2021-07-01 00:53
Uncaught TypeError: Cannot read property 'render' of undefined
    at Object.parcelRequire.App.js.react (App.js:30)
    at newRequire (App.d36a57b6.js:47)
    at App.d36a57b6.js:81
    at App.d36a57b6.js:120


###This is the error/
